# Blog settings
permalink: /:title


# My variables
name: blockloop.io
description: Musings and things I dwell on
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  input: GFM
  hard_wrap: false
highlighter: rouge
